/*GRANT CREATE SESSION TO FTEST;
GRANT CREATE VIEW TO FTEST;				
GRANT CREATE SYNONYM TO FTEST;
*/
GRANT SELECT ON  SAUD.CALL_LOG TO FRONT_END;
GRANT SELECT ON  SAUD.DATES TO FRONT_END;
GRANT SELECT ON  SAUD.DAY_WISE_ANALYSIS TO FRONT_END;
GRANT SELECT ON  SAUD.HOUR_WISE_ANALYSIS TO FRONT_END;
GRANT SELECT ON  SAUD.LONGEST_CALL TO FRONT_END;
GRANT SELECT ON  SAUD.MONTHLY_WISE_ANALYSIS TO FRONT_END;
GRANT SELECT ON  SAUD.MONTH_WISE_ANALYSIS TO FRONT_END;
GRANT SELECT ON  SAUD.SUMMARY TO FRONT_END;
GRANT SELECT ON  SAUD.TOP_10_CALLS TO FRONT_END;
GRANT SELECT ON  SAUD.TOP_10_I_COUNT TO FRONT_END;
GRANT SELECT ON  SAUD.TOP_10_I_DURATION TO FRONT_END;
GRANT SELECT ON  SAUD.TOP_10_M_COUNT TO FRONT_END;
GRANT SELECT ON  SAUD.TOP_10_O_COUNT TO FRONT_END;
GRANT SELECT ON  SAUD.TOP_10_O_DURATION TO FRONT_END;
GRANT SELECT ON  SAUD.WEEK_WISE_ANALYSIS TO FRONT_END;
GRANT SELECT ON  SAUD.YEAR_WISE_ANALYSIS TO FRONT_END;
GRANT INSERT,SELECT ON  SAUD.UPLOAD_LOG TO FRONT_END;

GRANT EXECUTE ON  SAUD.GET_NUMBER_TYPE TO FRONT_END;
GRANT EXECUTE ON  SAUD.LOGIN_CRE_P TO FRONT_END;
GRANT EXECUTE ON  SAUD.LOG_IN TO FRONT_END;
GRANT EXECUTE ON  SAUD.LOG_OUT TO FRONT_END;
GRANT EXECUTE ON  SAUD.UPDATE_DATES TO FRONT_END;

GRANT EXECUTE ON  SAUD.INSERT_TO_CALL_LOG TO FRONT_END;