DROP VIEW TOP_10_I_COUNT;
DROP VIEW TOP_10_O_COUNT;
DROP VIEW TOP_10_I_DURATION;
DROP VIEW TOP_10_O_DURATION;
DROP VIEW LONGEST_CALL;
DROP VIEW SUMMARY;
DROP VIEW TOP_10_M_COUNT;
DROP VIEW TOP_10_CALLS;
DROP VIEW CALL_LOG;



DROP SYNONYM INSERT_TO_CALL_LOG;
DROP SYNONYM DATES;
DROP SYNONYM LOG_IN;
DROP SYNONYM LOG_OUT;
--DROP SYNONYM CALL_LOG;
DROP SYNONYM CHECK_TABLE;
DROP SYNONYM GET_NUMBER_TYPE;

