REVOKE SELECT ON LONGEST_CALL FROM FRONT_END;
REVOKE SELECT ON SUMMARY FROM FRONT_END;
REVOKE SELECT ON TOP_10_CALLS FROM FRONT_END;
REVOKE SELECT ON TOP_10_I_COUNT FROM FRONT_END;
REVOKE SELECT ON TOP_10_I_DURATION FROM FRONT_END;
REVOKE SELECT ON TOP_10_M_COUNT FROM FRONT_END;
REVOKE SELECT ON TOP_10_O_COUNT FROM FRONT_END;
REVOKE SELECT ON TOP_10_O_DURATION FROM FRONT_END;
REVOKE INSERT,SELECT ON DATES FROM FRONT_END;
REVOKE EXECUTE ON log_in FROM FRONT_END;
REVOKE EXECUTE ON log_out FROM FRONT_END;
REVOKE EXECUTE ON INSERT_TO_CALL_LOG FROM FRONT_END;

DROP SYNONYM LONGEST_CALL;
DROP SYNONYM SUMMARY;
DROP SYNONYM TOP_10_CALLS;
DROP SYNONYM TOP_10_I_COUNT;
DROP SYNONYM TOP_10_I_DURATION;
DROP SYNONYM TOP_10_M_COUNT;
DROP SYNONYM TOP_10_O_COUNT;
DROP SYNONYM TOP_10_O_DURATION;
DROP SYNONYM INSERT_TO_CALL_LOG;
DROP SYNONYM DATES;
DROP SYNONYM log_in;
DROP SYNONYM log_out;

DROP TRIGGER call_log_audit_trg;
DROP FUNCTION get_number_type;
DROP PROCEDURE insert_to_call_log;
DROP PROCEDURE to_log;
DROP PROCEDURE log_in;
DROP PROCEDURE log_out;

DROP SEQUENCE seq_cl;
DROP SEQUENCE log_cl;
DROP SEQUENCE call_log_audit_seq;

DROP VIEW TOP_10_I_COUNT;
DROP VIEW TOP_10_O_COUNT;
DROP VIEW TOP_10_I_DURATION;
DROP VIEW TOP_10_O_DURATION;
DROP VIEW LONGEST_CALL;
DROP VIEW SUMMARY;
DROP VIEW TOP_10_M_COUNT;
DROP VIEW TOP_10_CALLS;


DROP INDEX i_contact_log;
DROP INDEX d_call_date_index;


DROP TABLE call_log;
DROP TABLE QUERY_LOG;
DROP TABLE dates;
DROP TABLE xla_reference_structure;
DROP TABLE CHECK_TABLE;
DROP TABLE call_log_audit;