CREATE OR REPLACE VIEW TOP_10_CALLS
AS 
SELECT COALESCE(NAME,PNUMBER) NAME,PNUMBER,ROUND(SUM(DURATION)/60,2) TOTAL_DURATION,COUNT(*) TOTAL_COUNT,TYPE 
FROM CALL_LOG
WHERE DURATION <> 0
AND TRUNC(D_CALL_DATE) BETWEEN (SELECT NVL(MAX(START_DATE),'01-JAN-2015') FROM DATES) AND (SELECT NVL(MAX(END_DATE),SYSDATE) FROM DATES)  
GROUP BY PNUMBER,NAME,TYPE;



CREATE OR REPLACE VIEW TOP_10_I_COUNT
AS 
SELECT "NAME","PNUMBER","TOTAL_DURATION","TOTAL_COUNT","TYPE" FROM (SELECT * FROM TOP_10_CALLS WHERE LOWER(TYPE) = 'INCOMING'
ORDER BY TOTAL_COUNT DESC) WHERE ROWNUM <= 10;



CREATE OR REPLACE VIEW TOP_10_O_COUNT
AS 
SELECT "NAME","PNUMBER","TOTAL_DURATION","TOTAL_COUNT","TYPE" FROM (SELECT * FROM TOP_10_CALLS WHERE LOWER(TYPE) = 'OUTGOING'
ORDER BY TOTAL_COUNT DESC) WHERE ROWNUM <= 10;



CREATE OR REPLACE VIEW TOP_10_I_DURATION
AS 
SELECT "NAME","PNUMBER","TOTAL_DURATION","TOTAL_COUNT","TYPE" FROM (SELECT * FROM TOP_10_CALLS WHERE LOWER(TYPE) = 'INCOMING'
ORDER BY TOTAL_DURATION DESC) WHERE ROWNUM <= 10;



CREATE OR REPLACE VIEW TOP_10_O_DURATION
AS 
SELECT "NAME","PNUMBER","TOTAL_DURATION","TOTAL_COUNT","TYPE" FROM (SELECT * FROM TOP_10_CALLS WHERE LOWER(TYPE) = 'OUTGOING'
ORDER BY TOTAL_DURATION DESC) WHERE ROWNUM <= 10;



CREATE OR REPLACE VIEW LONGEST_CALL
AS 
SELECT NAME,ROUND(TO_NUMBER(DURATION)/60,2) DURATION FROM CALL_LOG
WHERE DURATION IN (SELECT MAX(TO_NUMBER(DURATION)) FROM CALL_LOG);



CREATE OR REPLACE VIEW SUMMARY
AS 
SELECT 'ALL CALLS' TYPE,COUNT(*) COUNT FROM CALL_LOG
UNION ALL
SELECT 'MISSED CALLS' TYPE,COUNT(*) COUNT FROM CALL_LOG WHERE LOWER(TYPE) = 'MISSED'
UNION ALL
SELECT 'INCOMING CALLS' TYPE,COUNT(*) COUNT FROM CALL_LOG WHERE LOWER(TYPE) = 'INCOMING'
UNION ALL
SELECT 'OUTGOING CALLS' TYPE,COUNT(*) COUNT FROM CALL_LOG WHERE LOWER(TYPE) = 'OUTGOING'
UNION ALL
SELECT 'MOBILE CALLS' TYPE,COUNT(*) COUNT FROM CALL_LOG WHERE GET_NUMBER_TYPE(PNUMBER) IN (3,5)
UNION ALL
SELECT 'LANDLINE CALLS' TYPE,COUNT(*) COUNT FROM CALL_LOG WHERE GET_NUMBER_TYPE(PNUMBER) IN (2)
UNION ALL
SELECT 'INTERNATIONAL CALLS' TYPE,COUNT(*) COUNT FROM CALL_LOG WHERE GET_NUMBER_TYPE(PNUMBER) IN (6)
UNION ALL
SELECT 'OTHER CALLS' TYPE,COUNT(*) COUNT FROM CALL_LOG WHERE GET_NUMBER_TYPE(PNUMBER) NOT IN (2,3,5,6);



CREATE OR REPLACE VIEW TOP_10_M_COUNT
AS 
SELECT "NAME","PNUMBER","TOTAL_DURATION","TOTAL_COUNT","TYPE" FROM (
SELECT NAME,PNUMBER,'0' TOTAL_DURATION,COUNT(*) TOTAL_COUNT,TYPE 
FROM CALL_LOG
WHERE LOWER(TYPE) = 'MISSED'
GROUP BY PNUMBER,NAME,TYPE
ORDER BY TOTAL_COUNT DESC
) WHERE ROWNUM <= 10;


