CREATE OR REPLACE SYNONYM LONGEST_CALL FOR SAUD.LONGEST_CALL;
CREATE OR REPLACE SYNONYM SUMMARY FOR SAUD.SUMMARY;
CREATE OR REPLACE SYNONYM TOP_10_CALLS FOR SAUD.TOP_10_CALLS;
CREATE OR REPLACE SYNONYM TOP_10_I_COUNT FOR SAUD.TOP_10_I_COUNT;
CREATE OR REPLACE SYNONYM TOP_10_I_DURATION FOR SAUD.TOP_10_I_DURATION;
CREATE OR REPLACE SYNONYM TOP_10_M_COUNT FOR SAUD.TOP_10_M_COUNT;
CREATE OR REPLACE SYNONYM TOP_10_O_COUNT FOR SAUD.TOP_10_O_COUNT;
CREATE OR REPLACE SYNONYM TOP_10_O_DURATION FOR SAUD.TOP_10_O_DURATION;
CREATE OR REPLACE SYNONYM INSERT_TO_CALL_LOG FOR SAUD.INSERT_TO_CALL_LOG;
CREATE OR REPLACE SYNONYM DATES FOR SAUD.DATES;
CREATE OR REPLACE SYNONYM log_in FOR SAUD.log_in;
CREATE OR REPLACE SYNONYM log_out FOR SAUD.log_out;

--<S date=21-08-2015 Dev=Saud>
CREATE OR REPLACE SYNONYM INSERT_TO_CALL_LOG FOR SAUD.INSERT_TO_CALL_LOG;
CREATE OR REPLACE SYNONYM CALL_LOG FOR SAUD.CALL_LOG;
CREATE OR REPLACE SYNONYM CHECK_TABLE FOR SAUD.CHECK_TABLE;
CREATE OR REPLACE SYNONYM DATES FOR SAUD.DATES;
CREATE OR REPLACE SYNONYM GET_NUMBER_TYPE FOR SAUD.GET_NUMBER_TYPE;
CREATE OR REPLACE SYNONYM LOG_IN FOR SAUD.LOG_IN;
CREATE OR REPLACE SYNONYM LOG_OUT FOR SAUD.LOG_OUT;

 create synonym update_dates for saud.update_dates 
 create synonym login_cre_p for saud.login_cre_p
 
--<E>