-- CREATE OR REPLACE SYNONYM LONGEST_CALL FOR TEST.LONGEST_CALL;
-- CREATE OR REPLACE SYNONYM SUMMARY FOR TEST.SUMMARY;
-- CREATE OR REPLACE SYNONYM TOP_10_CALLS FOR TEST.TOP_10_CALLS;
-- CREATE OR REPLACE SYNONYM TOP_10_I_COUNT FOR TEST.TOP_10_I_COUNT;
-- CREATE OR REPLACE SYNONYM TOP_10_I_DURATION FOR TEST.TOP_10_I_DURATION;
-- CREATE OR REPLACE SYNONYM TOP_10_M_COUNT FOR TEST.TOP_10_M_COUNT;
-- CREATE OR REPLACE SYNONYM TOP_10_O_COUNT FOR TEST.TOP_10_O_COUNT;
-- CREATE OR REPLACE SYNONYM TOP_10_O_DURATION FOR TEST.TOP_10_O_DURATION;
-- CREATE OR REPLACE SYNONYM INSERT_TO_CALL_LOG FOR TEST.INSERT_TO_CALL_LOG;
-- CREATE OR REPLACE SYNONYM DATES FOR TEST.DATES;
-- CREATE OR REPLACE SYNONYM log_in FOR TEST.log_in;
-- CREATE OR REPLACE SYNONYM log_out FOR TEST.log_out;

--<S date=21-08-2015 Dev=Saud>
CREATE OR REPLACE SYNONYM INSERT_TO_CALL_LOG FOR TEST.INSERT_TO_CALL_LOG;
CREATE OR REPLACE SYNONYM CALL_LOG FOR TEST.CALL_LOG;
CREATE OR REPLACE SYNONYM CHECK_TABLE FOR TEST.CHECK_TABLE;
CREATE OR REPLACE SYNONYM DATES FOR TEST.DATES;
CREATE OR REPLACE SYNONYM GET_NUMBER_TYPE FOR TEST.GET_NUMBER_TYPE;
CREATE OR REPLACE SYNONYM LOG_IN FOR TEST.LOG_IN;
CREATE OR REPLACE SYNONYM LOG_OUT FOR TEST.LOG_OUT;

--<E>