--VIEWS
CREATE OR REPLACE SYNONYM FRONT_END.DAY_WISE_ANALYSIS FOR SAUD.DAY_WISE_ANALYSIS;
CREATE OR REPLACE SYNONYM FRONT_END.HOUR_WISE_ANALYSIS FOR SAUD.HOUR_WISE_ANALYSIS;
CREATE OR REPLACE SYNONYM FRONT_END.LONGEST_CALL FOR SAUD.LONGEST_CALL;
CREATE OR REPLACE SYNONYM FRONT_END.MONTHLY_WISE_ANALYSIS FOR SAUD.MONTHLY_WISE_ANALYSIS;
CREATE OR REPLACE SYNONYM FRONT_END.MONTH_WISE_ANALYSIS FOR SAUD.MONTH_WISE_ANALYSIS;
CREATE OR REPLACE SYNONYM FRONT_END.SUMMARY FOR SAUD.SUMMARY;
CREATE OR REPLACE SYNONYM FRONT_END.TOP_10_CALLS FOR SAUD.TOP_10_CALLS;
CREATE OR REPLACE SYNONYM FRONT_END.TOP_10_I_COUNT FOR SAUD.TOP_10_I_COUNT;
CREATE OR REPLACE SYNONYM FRONT_END.TOP_10_I_DURATION FOR SAUD.TOP_10_I_DURATION;
CREATE OR REPLACE SYNONYM FRONT_END.TOP_10_M_COUNT FOR SAUD.TOP_10_M_COUNT;
CREATE OR REPLACE SYNONYM FRONT_END.TOP_10_O_COUNT FOR SAUD.TOP_10_O_COUNT;
CREATE OR REPLACE SYNONYM FRONT_END.TOP_10_O_DURATION FOR SAUD.TOP_10_O_DURATION;
CREATE OR REPLACE SYNONYM FRONT_END.WEEK_WISE_ANALYSIS FOR SAUD.WEEK_WISE_ANALYSIS;
CREATE OR REPLACE SYNONYM FRONT_END.YEAR_WISE_ANALYSIS FOR SAUD.YEAR_WISE_ANALYSIS;
--TABLES
CREATE OR REPLACE SYNONYM FRONT_END.CALL_LOG FOR SAUD.CALL_LOG;
CREATE OR REPLACE SYNONYM FRONT_END.DATES FOR SAUD.DATES;
CREATE OR REPLACE SYNONYM FRONT_END.UPLOAD_LOG FOR SAUD.UPLOAD_LOG;
--PROCEDURES
CREATE OR REPLACE SYNONYM FRONT_END.LOG_IN FOR SAUD.LOG_IN;
CREATE OR REPLACE SYNONYM FRONT_END.LOG_OUT FOR SAUD.LOG_OUT;
CREATE OR REPLACE SYNONYM FRONT_END.UPDATE_DATES FOR SAUD.UPDATE_DATES; 
--FUNCTIONS
CREATE OR REPLACE SYNONYM FRONT_END.GET_NUMBER_TYPE FOR SAUD.GET_NUMBER_TYPE;
CREATE OR REPLACE SYNONYM FRONT_END.LOGIN_CRE_P FOR SAUD.LOGIN_CRE_P;
CREATE OR REPLACE SYNONYM FRONT_END.INSERT_TO_CALL_LOG FOR SAUD.INSERT_TO_CALL_LOG;