CREATE OR REPLACE VIEW CALL_LOG
AS
	SELECT * FROM (
	SELECT * FROM TEST.CALL_LOG
	)
	WHERE EXISTS (SELECT 1 FROM CHECK_TABLE WHERE ROWNUM <= 1);

CREATE OR REPLACE VIEW TOP_10_CALLS
AS 
	SELECT * FROM (
	SELECT COALESCE(NAME,PNUMBER) NAME,PNUMBER,ROUND(SUM(DURATION)/60,2) TOTAL_DURATION,COUNT(*) TOTAL_COUNT,TYPE 
	FROM CALL_LOG
	WHERE DURATION <> 0
	AND TRUNC(D_CALL_DATE) BETWEEN (SELECT NVL(MAX(START_DATE),'01-JAN-2015') FROM DATES) AND (SELECT NVL(MAX(END_DATE),SYSDATE) FROM DATES)  
	GROUP BY PNUMBER,COALESCE(NAME,PNUMBER),TYPE
	)
	WHERE EXISTS (SELECT 1 FROM CHECK_TABLE WHERE ROWNUM <= 1);



CREATE OR REPLACE VIEW TOP_10_I_COUNT
AS 
	SELECT * FROM (
	SELECT "NAME","PNUMBER","TOTAL_DURATION","TOTAL_COUNT","TYPE" FROM (SELECT * FROM TOP_10_CALLS WHERE UPPER(TYPE) = 'INCOMING'
	ORDER BY TOTAL_COUNT DESC) WHERE ROWNUM <= 10
	)
	WHERE EXISTS (SELECT 1 FROM CHECK_TABLE WHERE ROWNUM <= 1);



CREATE OR REPLACE VIEW TOP_10_O_COUNT
AS 
	SELECT * FROM (
	SELECT "NAME","PNUMBER","TOTAL_DURATION","TOTAL_COUNT","TYPE" FROM (SELECT * FROM TOP_10_CALLS WHERE UPPER(TYPE) = 'OUTGOING'
	ORDER BY TOTAL_COUNT DESC) WHERE ROWNUM <= 10
	)
	WHERE EXISTS (SELECT 1 FROM CHECK_TABLE WHERE ROWNUM <= 1);



CREATE OR REPLACE VIEW TOP_10_I_DURATION
AS 
	SELECT * FROM (
	SELECT "NAME","PNUMBER","TOTAL_DURATION","TOTAL_COUNT","TYPE" FROM (SELECT * FROM TOP_10_CALLS WHERE UPPER(TYPE) = 'INCOMING'
	ORDER BY TOTAL_DURATION DESC) WHERE ROWNUM <= 10
	)
	WHERE EXISTS (SELECT 1 FROM CHECK_TABLE WHERE ROWNUM <= 1);



CREATE OR REPLACE VIEW TOP_10_O_DURATION
AS 
	SELECT * FROM (
	SELECT "NAME","PNUMBER","TOTAL_DURATION","TOTAL_COUNT","TYPE" FROM (SELECT * FROM TOP_10_CALLS WHERE UPPER(TYPE) = 'OUTGOING'
	ORDER BY TOTAL_DURATION DESC) WHERE ROWNUM <= 10
	)
	WHERE EXISTS (SELECT 1 FROM CHECK_TABLE WHERE ROWNUM <= 1);



CREATE OR REPLACE VIEW LONGEST_CALL
AS 
	SELECT * FROM (
	SELECT COALESCE(NAME,PNUMBER) NAME,ROUND(TO_NUMBER(DURATION)/60,2) DURATION FROM CALL_LOG
	WHERE DURATION IN (SELECT MAX(TO_NUMBER(DURATION)) FROM CALL_LOG WHERE TRUNC(D_CALL_DATE) BETWEEN (SELECT NVL(MAX(START_DATE),'01-JAN-2015') FROM DATES) AND (SELECT NVL(MAX(END_DATE),SYSDATE) FROM DATES))
	--AND TRUNC(D_CALL_DATE) BETWEEN (SELECT NVL(MAX(START_DATE),'01-JAN-2015') FROM DATES) AND (SELECT NVL(MAX(END_DATE),SYSDATE) FROM DATES)  --mofidied on 04-Sep-2015
	)
	WHERE EXISTS (SELECT 1 FROM CHECK_TABLE WHERE ROWNUM <= 1);



CREATE OR REPLACE VIEW SUMMARY
AS 
	SELECT * FROM (
	SELECT 'ALL CALLS' TYPE,COUNT(*) COUNT FROM CALL_LOG WHERE TRUNC(D_CALL_DATE) BETWEEN (SELECT NVL(MAX(START_DATE),'01-JAN-2015') FROM DATES) AND (SELECT NVL(MAX(END_DATE),SYSDATE) FROM DATES)  
	UNION ALL
	SELECT 'MISSED CALLS' TYPE,COUNT(*) COUNT FROM CALL_LOG WHERE UPPER(TYPE) = 'MISSED' AND TRUNC(D_CALL_DATE) BETWEEN (SELECT NVL(MAX(START_DATE),'01-JAN-2015') FROM DATES) AND (SELECT NVL(MAX(END_DATE),SYSDATE) FROM DATES)  
	UNION ALL
	SELECT 'INCOMING CALLS' TYPE,COUNT(*) COUNT FROM CALL_LOG WHERE UPPER(TYPE) = 'INCOMING' AND TRUNC(D_CALL_DATE) BETWEEN (SELECT NVL(MAX(START_DATE),'01-JAN-2015') FROM DATES) AND (SELECT NVL(MAX(END_DATE),SYSDATE) FROM DATES)  
	UNION ALL
	SELECT 'OUTGOING CALLS' TYPE,COUNT(*) COUNT FROM CALL_LOG WHERE UPPER(TYPE) = 'OUTGOING' AND TRUNC(D_CALL_DATE) BETWEEN (SELECT NVL(MAX(START_DATE),'01-JAN-2015') FROM DATES) AND (SELECT NVL(MAX(END_DATE),SYSDATE) FROM DATES)  
	UNION ALL
	SELECT 'MOBILE CALLS' TYPE,COUNT(*) COUNT FROM CALL_LOG WHERE GET_NUMBER_TYPE(PNUMBER) IN (3,5) AND TRUNC(D_CALL_DATE) BETWEEN (SELECT NVL(MAX(START_DATE),'01-JAN-2015') FROM DATES) AND (SELECT NVL(MAX(END_DATE),SYSDATE) FROM DATES)  
	UNION ALL
	SELECT 'LANDLINE CALLS' TYPE,COUNT(*) COUNT FROM CALL_LOG WHERE GET_NUMBER_TYPE(PNUMBER) IN (2) AND TRUNC(D_CALL_DATE) BETWEEN (SELECT NVL(MAX(START_DATE),'01-JAN-2015') FROM DATES) AND (SELECT NVL(MAX(END_DATE),SYSDATE) FROM DATES)  
	UNION ALL
	SELECT 'INTERNATIONAL CALLS' TYPE,COUNT(*) COUNT FROM CALL_LOG WHERE GET_NUMBER_TYPE(PNUMBER) IN (6) AND TRUNC(D_CALL_DATE) BETWEEN (SELECT NVL(MAX(START_DATE),'01-JAN-2015') FROM DATES) AND (SELECT NVL(MAX(END_DATE),SYSDATE) FROM DATES)  
	UNION ALL
	SELECT 'OTHER CALLS' TYPE,COUNT(*) COUNT FROM CALL_LOG WHERE GET_NUMBER_TYPE(PNUMBER) NOT IN (2,3,5,6) AND TRUNC(D_CALL_DATE) BETWEEN (SELECT NVL(MAX(START_DATE),'01-JAN-2015') FROM DATES) AND (SELECT NVL(MAX(END_DATE),SYSDATE) FROM DATES)  
	)
	WHERE EXISTS (SELECT 1 FROM CHECK_TABLE WHERE ROWNUM <= 1);


CREATE OR REPLACE VIEW TOP_10_M_COUNT
AS 
	SELECT * FROM (
	SELECT "NAME","PNUMBER","TOTAL_DURATION","TOTAL_COUNT","TYPE" FROM (
	SELECT COALESCE(NAME,PNUMBER) NAME,PNUMBER,'0' TOTAL_DURATION,COUNT(*) TOTAL_COUNT,TYPE 
	FROM CALL_LOG
	WHERE UPPER(TYPE) = 'MISSED'
	AND TRUNC(D_CALL_DATE) BETWEEN (SELECT NVL(MAX(START_DATE),'01-JAN-2015') FROM DATES) AND (SELECT NVL(MAX(END_DATE),SYSDATE) FROM DATES)  
	GROUP BY PNUMBER,COALESCE(NAME,PNUMBER),TYPE
	ORDER BY TOTAL_COUNT DESC
	) WHERE ROWNUM <= 10
	)
	WHERE EXISTS (SELECT 1 FROM CHECK_TABLE WHERE ROWNUM <= 1);
	

