DROP USER TEST CASCADE;
DROP USER FTEST CASCADE;
DROP ROLE TESTER;

CREATE USER TEST IDENTIFIED BY TEST;
CREATE USER FTEST IDENTIFIED BY FTEST;
CREATE ROLE TESTER;
GRANT CREATE SESSION,CREATE TABLE,CREATE VIEW,CREATE PROCEDURE,CREATE TRIGGER,CREATE SEQUENCE, GRANT ANY PRIVILEGE TO TESTER;
ALTER USER TEST QUOTA 100M ON SYSTEM ;
GRANT UNLIMITED TABLESPACE TO TEST;

GRANT TESTER TO TEST;

GRANT CREATE SYNONYM,CREATE VIEW TO FTEST;
