CREATE OR REPLACE SYNONYM LONGEST_CALL FOR SAUD.LONGEST_CALL;
CREATE OR REPLACE SYNONYM SUMMARY FOR SAUD.SUMMARY;
CREATE OR REPLACE SYNONYM TOP_10_CALLS FOR SAUD.TOP_10_CALLS;
CREATE OR REPLACE SYNONYM TOP_10_I_COUNT FOR SAUD.TOP_10_I_COUNT;
CREATE OR REPLACE SYNONYM TOP_10_I_DURATION FOR SAUD.TOP_10_I_DURATION;
CREATE OR REPLACE SYNONYM TOP_10_M_COUNT FOR SAUD.TOP_10_M_COUNT;
CREATE OR REPLACE SYNONYM TOP_10_O_COUNT FOR SAUD.TOP_10_O_COUNT;
CREATE OR REPLACE SYNONYM TOP_10_O_DURATION FOR SAUD.TOP_10_O_DURATION;
CREATE OR REPLACE SYNONYM INSERT_TO_CALL_LOG FOR SAUD.INSERT_TO_CALL_LOG;

CREATE OR REPLACE SYNONYM DATES FOR SAUD.DATES;

CREATE OR REPLACE SYNONYM log_in FOR SAUD.log_in;
CREATE OR REPLACE SYNONYM log_out FOR SAUD.log_out;

GRANT SELECT ON LONGEST_CALL TO FRONT_END;
GRANT SELECT ON SUMMARY TO FRONT_END;
GRANT SELECT ON TOP_10_CALLS TO FRONT_END;
GRANT SELECT ON TOP_10_I_COUNT TO FRONT_END;
GRANT SELECT ON TOP_10_I_DURATION TO FRONT_END;
GRANT SELECT ON TOP_10_M_COUNT TO FRONT_END;
GRANT SELECT ON TOP_10_O_COUNT TO FRONT_END;
GRANT SELECT ON TOP_10_O_DURATION TO FRONT_END;

GRANT SELECT ON DATES TO FRONT_END;

GRANT CREATE SESSION TO FRONT_END;
GRANT CREATE SYNONYM TO FRONT_END;

GRANT EXECUTE ON log_in TO FRONT_END;
GRANT EXECUTE ON log_out TO FRONT_END;
GRANT EXECUTE ON INSERT_TO_CALL_LOG TO FRONT_END;

COMMIT;